Vagrant.configure("2") do |config|
  config.vm.box_check_update = false
  #config.ssh.private_key_path = "cluster_key"

  NETWORK_PREFIX = "192.168.56"

  # =========================
  # LINUX NODES
  # =========================

  [
    ["linux1", 11],
    ["linux2", 12]
  ].each do |name, id|
    config.vm.define name do |node|
      node.vm.box = "ubuntu/jammy64"
      node.vm.hostname = name
      node.vm.network "private_network", ip: "#{NETWORK_PREFIX}.#{id}"

      node.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 1
      end

      node.vm.provision "shell", path: "scripts/install_cluster_key.sh"
      node.vm.provision "shell", path: "scripts/install_scanner_linux.sh"
    end
  end

  # =========================
  # DNS SERVER
  # =========================
  config.vm.define "dns" do |dns|
    dns.vm.box = "ubuntu/jammy64"
    dns.vm.hostname = "dns"
    dns.vm.network "private_network", ip: "#{NETWORK_PREFIX}.20"

    dns.vm.provider "virtualbox" do |vb|
      vb.memory = 768
      vb.cpus = 1
    end

    dns.vm.provision "shell", path: "scripts/install_cluster_key.sh"
    dns.vm.provision "shell", path: "scripts/install_scanner_dns.sh"
  end

  # =========================
  # FIREWALL
  # =========================
  config.vm.define "firewall" do |fw|
    fw.vm.box = "ubuntu/jammy64"
    fw.vm.hostname = "firewall"
    fw.vm.network "private_network", ip: "#{NETWORK_PREFIX}.30"

    fw.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
    end

    fw.vm.provision "shell", path: "scripts/install_cluster_key.sh"
    fw.vm.provision "shell", path: "scripts/install_scanner_firewall.sh"
  end

  # =========================
  # PRINTER
  # =========================
  config.vm.define "printer" do |pr|
    pr.vm.box = "ubuntu/jammy64"
    pr.vm.hostname = "printer"
    pr.vm.network "private_network", ip: "#{NETWORK_PREFIX}.40"

    pr.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
    end

    pr.vm.provision "shell", path: "scripts/install_cluster_key.sh"
    pr.vm.provision "shell", path: "scripts/install_scanner_printer.sh"
  end

  # =========================
  # WINDOWS CLIENT (SSH ENABLED)
  # =========================
  config.vm.define "win" do |win|
    win.vm.box = "jborean93/WindowsServer2022"
    win.vm.hostname = "win-client"
    win.vm.network "private_network", ip: "#{NETWORK_PREFIX}.50"

    win.vm.communicator = "winrm"
    win.vm.boot_timeout = 1200

    win.vm.provider "virtualbox" do |vb|
        vb.memory = 4096
        vb.cpus = 2
        vb.gui = true
        vb.customize ["modifyvm", :id, "--graphicscontroller", "vboxsvga"]
        vb.customize ["modifyvm", :id, "--vram", "128"]
    end

        win.vm.provision "shell", privileged: true, path: "scripts/install_cluster_key_windows.ps1"
        win.vm.provision "shell", privileged: true, path: "scripts/install_scanner_windows.ps1"
    end
end